blazer/app/views/blazer/queries/show.html.erb
blazer/config/application.rb

Update the log format to JSON so that it can handle newlines in logged data as a single entry.
Also re-enables the `Download` button on queries with a reminder to be careful with data that is downloaded.
- cds-snc/platform-core-services#179

fix: switch to JSON logging

---

.github/workflows/docker-build-and-push.yml
.github/workflows/docker-vulnerability-scan.yml

Add a nightly Docker vulnerability scan and Docker image generate SBOM step.  This will publish security findings and Docker image asset inventories to GitHub.
- cds-snc/platform-core-services#204

feat: add Docker generate SBOM and vulnerability scan

---

.github/workflows/docker-build-and-push.yml
.github/workflows/docker-vulnerability-scan.yml

Update the security tools actions to the version which increases the Trivy timeout to 15 minutes.
- cds-snc/platform-core-services#204
- #25

fix: bump Docker scan and SBOM action versions

---

blazer/.env.example
blazer/README.md
blazer/app/models/audit.rb
blazer/docker-compose.yml

In #14 we added Cloudwatch logging to the auditing, however the `query` variable does not exist for running in the edit screen. We can still log the user and what they ran, however.
Also changed `docker-compose.yml` so that it would run and connect to the Notify database running locally in a devcontainer. I don't think this will affect running in staging or production?
set up an appropriate `.env` and run `docker-compose up`. See the [README](https://github.com/cds-snc/notification-lambdas/blob/main/blazer/README.md) for more details.

hook up to notify devcontainer db and fix audit error

---

blazer/config/blazer.yml

This PR adds the slack configuration to blazer and passes an existing slack webhook in from secrets as a test.  Once the functionality is working, we can plumb this properly with a new webhook that we will need to setup.

feat(slack): add slack webhook URL to

---

sesemailcallbacks/ses_to_sqs_email_callbacks.py

We had an incident today where the lambda timeout (1 minute) would kick off before the boto call to SQS timeout (default: 1m).
These changes make the connection timeout to 15 seconds with a max retry strategy of 3. Hence the connection has a total of ~45 seconds to establish a connection. If it gets past this time, the code will timeout prior the lambda running instance itself. This should yield better error message but also more reliability with the lambda as it should retry more than once.
I'll have to deploy to staging and monitor the situation with a bulk send of emails and their read receipts.

Tweaked connection timeout+max retried for SQS boto

---

system_status/requirements_for_system_status.txt

This bumps utils to make use of the extra logging added in [PR#266](https://github.com/cds-snc/notification-utils/pull/266)
IN STAGING:
- Simulate a site being down by changing one of the site urls to an invalid url
- Simulate email/sms sending is down by disabling heartbeat lambda for 5 minutes

Add extra logging to system status lambda

---

.github/workflows/docker-build-and-push.yml

This PR updates the `docker-build-and-push` action to fix a problem generating the docker SBOM due to logging out of ECR too early in the workflow.

fix: move sbom action to after logout

---

system_status/system_status.py

Explicitly set the logging level so that INFO logs make it into cloudwatch.

chore: set logging level explicitly

---

.github/workflows/docker-build-and-push.yml

There's an issue with the docker images not being in ECR but pr-bot wanting to release them. This could lead to a release that breaks heartbeat and the system_status page. Here we comment out the pr-bot part of the action so releases will not make lambda changes. After we've fixed the rest of the workflow we can put pr-bot back in.

temporarily remove pr-bot from workflow

---

catalog-info.yaml

Updating the kind of entity to Resource of type lambda, owner to notify-dev team, lifecycle to production.
Not applicable
None.

chore: update kind and owner

---

.github/workflows/test-format-lint.yml
heartbeat/Makefile
heartbeat/requirements.txt

There was a bug in the CI/Actions for the notification lambdas repository. Docker compose wasn't installed so that failed, and also there were issues with the make file when it tried to install some versions.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/420
CI on the notification lambda repo is working as expected
None.

Fixing Bug 420 -- Notification Lambdas repo

---

.github/workflows/test-format-lint.yml

Just pinning the version for the docker compose Github action
None.

pinning the docker compose action version

---

.github/workflows/docker-build-and-push.yml
.github/workflows/docker-vulnerability-scan.yml

Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
- https://github.com/cds-snc/platform-core-services/issues/597

fix: use CDS Trivy vulnerability database

---

.github/workflows/docker-build-and-push.yml
.github/workflows/docker-vulnerability-scan.yml

Update the Trivy actions to use a self-hosted version of the Trivy Java database artifact. 
* #88
* https://github.com/cds-snc/security-tools/pull/506
Expect that Docker vulnerability and SBOM scans using Trivy no longer fail with a `TOOMANYREQUESTS` error when fetching the Trivy Java database.
None.

fix: use self-hosted version of Trivy Java DB

---

pinpointsmscallbacks/Dockerfile
sesemailcallbacks/Dockerfile
sesreceivingemails/Dockerfile
snssmscallbacks/Dockerfile

Upgrade the following lambda functions to Python 3.12:
- `pinpointsmscallbacks`
- `snssmscallbacks`
- `sesemailcallbacks`
- `sesreceivingemails`
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/515
Verify locally that the images build with:
```
docker build -f pinpointsmscallbacks/Dockerfile .
docker build -f smscallbacks/Dockerfile .
docker build -f snssmscallbacks/Dockerfile .
docker build -f sesemailcallbacks/Dockerfile .
docker build -f sesreceivingemails/Dockerfile .
```
Testing if the functions still actually work will be done in staging.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify …

upgrade callbacks to Python 3.12

---

google-cidr/cidr.py

Getting an error `[ERROR] TypeError: handler() takes 0 positional arguments but 2 were given`. I think we broke it [here](https://github.com/cds-snc/notification-lambdas/commit/10952ad7246a93666ce79622bdd828f24d293cff#diff-8e8ea04a73fe6e8a1c3102bb768db9e8abe4f716f8e1494c28479a03bf7d22e7L100). This PR adds them back.
Note: not upgrading to Python 3.12 yet, just trying to fix first.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/517
Check logs for errors.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that …

add handler parameters to google_cidr

---

.github/workflows/docker-build-and-push.yml

Add the new filter logic to the prod part of the deployment. 
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1896
Workflows should run successfully when this is merged 🤞 

update the filter for the prod part of the workflow

---

.github/workflows/create-manifests-release-pr.yml
.github/workflows/docker-build-and-push.yml

The PR-bot was running [multiple times](https://github.com/cds-snc/notification-lambdas/actions/runs/15303621411/job/43052568030) when a PR was merged to main because of the matrix strategy used in docker-build-and-push.
This PR moves the pr-bot run out of the docker-build-and-push workflow so that it only runs once after the docker-build-and-push is done. 
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1896
After this is merged, the manifests pr should only be created once, after docker-build-and-push completes successfully.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, …

Fix issue where the PR-Bot is running multiple times

---

.github/workflows/docker-build-and-push.yml
.github/workflows/docker-build.yml

Rebuild lambdas if any files in the repo change
This was causing an issue where PR bot was including lambda changes in the release if any file in this repo was changed. But the lambdas were not being built unless a particular set of files changed. 
Lambda images should be rebuilt whenever any files in the repo change.

Rebuild lambdas if any files in the repo change
